name: Check Install

on:
  push:
  pull_request:

jobs:
  check-install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          export PREFIX="$RUNNER_TEMP/impf"
          mkdir -p "$PREFIX/bin"
          echo "$PREFIX/bin" >> "$GITHUB_PATH"
          make install

      - name: Install on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $InstallPath = Join-Path $env:RUNNER_TEMP "impf"
          New-Item -ItemType Directory -Force $InstallPath | Out-Null
          $env:PATH = "$InstallPath;$env:PATH"
          Add-Content $env:GITHUB_PATH $InstallPath

          ./install.ps1

      - name: Check impf is in PATH
        if: runner.os != 'Windows'
        shell: bash
        run: |
          command -v impf
          impf --help

      - name: Check impf is in PATH
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-Command impf
          impf --help
